# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f741791cde53c54687ccbe3da22cd843b9324f84a0889bd074d1fb1129de1da61ba50534df1f632a1c3a606d8b6e6c59a707a2f015c500ef1343fd371acbb52
  api_url: http://wtever-api:8080/v1

test:
  secret_key_base: 620a6cb6e66160c534f452625770a367e28dae11690d6e5878351d9482486983a1ffe3d445e448b0c11c39112bb7e658caae18cb4970af8aed8997d46ebb2ad4
  api_url: http://wtever-api:8080/v1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  api_url: http://wtever-api:8080/v1
